### ISSUE TITLE
Failed to install addon

### ISSUE THREAD

**Issue by rnauber** [OPHoperHPO/hassio-addons#2]
Thank you for creating this really useful piece of software!
But, with HA 2021.2.1 I get the following message:

> Failed to install addon
> The command '/bin/bash -o pipefail -c apk add --no-cache alsa-plugins-pulse alsa-utils pulseaudio-utils python3' returned a non-zero code: 4

**Comment by Toxminn** [comment]
same her ;(

**Comment by OPHoperHPO** [comment]
@rnauber, @Toxminn, can you send more logs or info if you have? I need the addon build logs, Home Assistant and Hass.IO logs immediately after the addon build error.

**Comment by Toxminn** [comment]
these are the only logs I have found

 ```
21-02-09 20:15:31 INFO (SyncWorker_1) [supervisor.docker.addon] Starting build for d4868bb1/armv7-addon-pulseaudio_fix:3.4
 21-02-09 20:15:38 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build d4868bb1/armv7-addon-pulseaudio_fix:3.4: The command '/bin/bash -o pipefail -c apk add --no-cache         alsa-plugins-pulse         alsa-utils         pulseaudio-utils         python3' returned a non-zero code: 4
 21-02-09 20:15:38 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
 Step 1/18 : ARG BUILD_FROM
 Step 2/18 : FROM $BUILD_FROM
  ---> 21461176cb52
 Step 3/18 : ENV LANG C.UTF-8
  ---> Using cache
  ---> 5034665d5511
 Step 4/18 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
  ---> Using cache
  ---> 60d26a57b57a
 Step 5/18 : ARG BUILD_ARCH=amd64
  ---> Using cache
  ---> df6362343391
 Step 6/18 : RUN     apk add --no-cache         alsa-plugins-pulse         alsa-utils         pulseaudio-utils         python3
  ---> Running in a14ae100c5dd
 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
 
 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
 
 ERROR: unable to select packages:
 
   alsa-plugins-pulse (no such package):
     required by: world[alsa-plugins-pulse]
   alsa-utils (no such package):
     required by: world[alsa-utils]
   pulseaudio-utils (no such package):
     required by: world[pulseaudio-utils]
   python3 (no such package):
     required by: world[python3]
 Removing intermediate container a14ae100c5dd
 
 21-02-09 20:15:50 INFO (MainThread) [supervisor.snapshots] Found 0 snapshot files
```

**Comment by rnauber** [comment]
I have got:
```

21-02-09 19:21:27 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build d4868bb1/armv7-addon-pulseaudio_fix:3.4: The command '/bin/bash -o pipefail -c apk add --no-cache         alsa-plugins-pulse         alsa-utils         pulseaudio-utils         python3' returned a non-zero code: 4
21-02-09 19:21:27 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/18 : ARG BUILD_FROM
Step 2/18 : FROM $BUILD_FROM
 ---> 21461176cb52
Step 3/18 : ENV LANG C.UTF-8
 ---> Using cache
 ---> 4780a57a0368
Step 4/18 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> 9d65cf57c8f2
Step 5/18 : ARG BUILD_ARCH=amd64
 ---> Using cache
 ---> 23d972c0484f
Step 6/18 : RUN     apk add --no-cache         alsa-plugins-pulse         alsa-utils         pulseaudio-utils         python3
 ---> Running in 1faef28f8787
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)

ERROR: unable to select packages:

  alsa-plugins-pulse (no such package):
    required by: world[alsa-plugins-pulse]
  alsa-utils (no such package):
    required by: world[alsa-utils]
  pulseaudio-utils (no such package):
    required by: world[pulseaudio-utils]
  python3 (no such package):
    required by: world[python3]
Removing intermediate container 1faef28f8787
```

**Comment by NdR91** [comment]
Same issue here:

`Failed to install addon`

`The command '/bin/bash -o pipefail -c apk add --no-cache alsa-plugins-pulse alsa-utils pulseaudio-utils python3' returned a non-zero code: 4`

**Comment by ChrisKolan** [comment]
I can confirm the issue.

**Comment by stanislavhannes** [comment]
I have it too after the update

**Comment by corgan2222** [comment]
same here.. i think this here broke with the latest ha.audio update from feb 15.
Any idead how to fix?

**Comment by OPHoperHPO** [comment]
@Toxminn, @stanislavhannes , @rnauber , @ChrisKolan , @corgan2222 , @NdR91 

At the moment I do not have a Hass.IO environment for testing the addon, so I need people who want to test it. I made some changes to the code, which in theory should fix the error, and moved them into a separate version - the dev version.
Try to install addon `Alsa & PulseAudio Fix dev version` from repository.

**Comment by corgan2222** [comment]
i tryed the dev version.

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> Connection failure: Connection refused
> pa_context_connect() failed: Connection refused
> [cmd] python3 exited 0
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.



but i still get the same wall of error text from HA pulseaudio

> 
> │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.                                                                                                                                               │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.                                                                                                                                                                         │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] core-util.c: setpriority() worked.                                                                                                                                                                                   │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] core-util.c: Successfully gained nice level -11.                                                                                                                                                                     │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] main.c: Found user 'root' (UID 0) and group 'root' (GID 0).                                                                                                                                                          │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: W: [pulseaudio] main.c: Home directory of user 'root' is not '/var/run/pulse', ignoring.                                                                                                                                             │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: W: [pulseaudio] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.                                                                       │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] main.c: Successfully changed user to "root".                                                                                                                                                                         │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] main.c: This is PulseAudio 14.2                                                                                                                                                                                      │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] main.c: Compilation CFLAGS: Not yet supported on meson                                                                                                                                                               │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] main.c: Running on host: Linux armv7l 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021                                                                                                                            │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] main.c: Found 4 CPUs.                                                                                                                                                                                                │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] main.c: Page size is 4096 bytes                                                                                                                                                                                      │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] main.c: Compiled with Valgrind support: no                                                                                                                                                                           │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] main.c: Running in valgrind mode: no                                                                                                                                                                                 │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] main.c: Running in VM: no                                                                                                                                                                                            │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] main.c: Running from build tree: no                                                                                                                                                                                  │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] main.c: Optimized build: yes                                                                                                                                                                                         │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] main.c: All asserts enabled.                                                                                                                                                                                         │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] main.c: Machine ID is hassio-audio.                                                                                                                                                                                  │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] main.c: Using runtime directory /var/run/pulse.                                                                                                                                                                      │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] main.c: Using state directory /data/states.                                                                                                                                                                          │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-14.2/modules.                                                                                                                                                         │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] main.c: Running in system mode: yes                                                                                                                                                                                  │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.                                                                                                             │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.                                      │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: W: [pulseaudio] pid.c: Stale PID file, overwriting.                                                                                                                                                                                  │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] main.c: System supports high resolution timers                                                                                                                                                                       │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] memblock.c: Using private memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65496                                                                               │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] cpu-arm.c: CPU flags: V6 V7 VFP EDSP NEON VFPV3                                                                                                                                                                      │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] svolume_arm.c: Initialising ARM optimized volume functions.                                                                                                                                                          │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] sconv_neon.c: Initialising ARM NEON optimized conversions.                                                                                                                                                           │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] mix_neon.c: Initialising ARM NEON optimized mixing functions.                                                                                                                                                        │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] remap_neon.c: Initialising ARM NEON optimized remappers.                                                                                                                                                             │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/hassio-audio-device-volumes.tdb'                                                                                                                                   │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] database.c: Successfully opened 'device-volumes' database file '/data/states/hassio-audio-device-volumes.tdb'.                                                                                                       │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] module.c: Loaded "module-device-restore" (index: #0; argument: "").                                                                                                                                                  │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/hassio-audio-stream-volumes.tdb'                                                                                                                                   │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] database.c: Successfully opened 'stream-volumes' database file '/data/states/hassio-audio-stream-volumes.tdb'.                                                                                                       │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] protocol-dbus.c: Interface org.PulseAudio.Ext.StreamRestore1 added for object /org/pulseaudio/stream_restore1                                                                                                        │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] module.c: Loaded "module-stream-restore" (index: #1; argument: "").                                                                                                                                                  │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/hassio-audio-card-database.tdb'                                                                                                                                    │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] database.c: Successfully opened 'card-database' database file '/data/states/hassio-audio-card-database.tdb'.                                                                                                         │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] module.c: Loaded "module-card-restore" (index: #2; argument: "").                                                                                                                                                    │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] module.c: Loaded "module-switch-on-port-available" (index: #3; argument: "").                                                                                                                                        │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: I: [pulseaudio] module.c: Loaded "module-switch-on-connect" (index: #4; argument: "").                                                                                                                                               │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] module-udev-detect.c: /dev/snd/controlC0 is accessible: yes                                                                                                                                                          │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card0: No such file or directory                                                                                                                                   │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: D: [pulseaudio] module-udev-detect.c: /devices/platform/soc/fe00b840.mailbox/bcm2835_audio/sound/card0 is busy: no                                                                                                                   │
> │Feb 21 23:21:38 homeassistant 254c16c1fd06[1098]: E: [pulseaudio] core-rtclock.c: Assertion 'clock_gettime(CLOCK_REALTIME, &ts) == 0' failed at ../src/pulsecore/core-rtclock.c:93, function pa_rtclock_get(). Aborting.   

I dont use audio at all.
Rasbian Buster 10 on RP4, full apt-get update&upgrade yesterday

Im wondering, is this fix for my problem. I dont get a "Device or resource busy" error.

**Comment by OPHoperHPO** [comment]
@corgan2222, Addon setup was finished successfully, so this issue was fixed. Wait for fix of your error, when issue #3 will be closed.

**Comment by corgan2222** [comment]
Thanks for the info and your work! I really appreciate!

**Comment by corgan2222** [comment]
Dominik.W could find the problem and a workaround for my bug
https://community.home-assistant.io/t/solved-hassio-audio-is-in-boot-loop-and-spams-my-syslog-with-errors/282538/49?u=corgan

this works great.

**Comment by NdR91** [comment]
I tried the dev version of the add-on and it worked perfectly!

**Comment by Toxminn** [comment]
> I tried the dev version of the add-on and it worked perfectly!

for me as well 
many thanks!

**Comment by jan-gerard** [comment]
I have the log-spam problem, every second pumping this line and some 15 others in the syslog file:

E: [pulseaudio] core-rtclock.c: Assertion 'clock_gettime(CLOCK_REALTIME, &ts) == 0' failed at ../src/pulsecore/core-rtclock.c:93, function pa_rtclock_get(). Aborting.

I applied the Fix dev version, but it appears intermittently running and stopped (the  addon_d4868bb1_pulseaudio_fix_dev container). Is can see in the logging of Docker:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
[cmd] python3 exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Supervisor is retrying continuously, but to success. I am now debugging a fix of another problem. I actually hope that the original problem will be solved somehow.

**Comment by jan-gerard** [comment]
Finally solved (or suppressed) the issue by applying https://community.home-assistant.io/t/solved-hassio-audio-is-in-boot-loop-and-spams-my-syslog-with-errors/282538/93

**Comment by user514** [comment]
Ok. Trying to install alsa pulseaudio fix addon on my new installation of HA (raspbian, supervised, docker, etc). July 2021. Got error ...installing version 3.4 from repo:

`The command '/bin/bash -o pipefail -c apk add --no-cache alsa-plugins-pulse alsa-utils pulseaudio-utils python3' returned a non-zero code: 4`

 Seeing this thread, tried v3.5 in dev version as suggested. Worked lake a charm!!!. Thanks.

Checked as I always do the CPU usage of hassio-audio container with:
`  # docker stats hassio_audio`

  To see if the problem was fixed, and got 0% CPU usage all the time, as always when addon is started and working. (not 16-22% CPU usage when alsa audio issue is taking place), . So problem fixed. Thanks OPHoperHPO.
